export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed-dim": "#95d3ba",
        "on-tertiary-fixed": "#331200",
        "primary-fixed": "#b0f0d6",
        "gold-spiritual": "#D97706",
        "surface-tint": "#2b6954",
        "surface-bright": "#f8faf6",
        "on-surface": "#191c1b",
        "secondary-fixed-dim": "#bacac3",
        "on-tertiary-container": "#ff985a",
        "inverse-surface": "#2e312f",
        "tertiary": "#502000",
        "on-secondary-container": "#566660",
        "inverse-on-surface": "#eff1ee",
        "emerald-deep": "#064E3B",
        "on-primary-fixed-variant": "#0b513d",
        "outline": "#707974",
        "on-background": "#191c1b",
        "tertiary-fixed-dim": "#ffb68e",
        "primary": "#003527",
        "outline-variant": "#bfc9c3",
        "surface-variant": "#e1e3e0",
        "surface-container-high": "#e7e9e5",
        "on-error-container": "#93000a",
        "background": "#f8faf6",
        "tertiary-container": "#733100",
        "secondary-container": "#d3e3dc",
        "error-container": "#ffdad6",
        "amber-soft": "#FDE68A",
        "surface-container-highest": "#e1e3e0",
        "mint-fresh": "#D1FAE5",
        "surface": "#f8faf6",
        "surface-white": "#FFFFFF",
        "on-tertiary-fixed-variant": "#763300",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbca",
        "on-primary-fixed": "#002117",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#101e1a",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dbd7",
        "on-error": "#ffffff",
        "inverse-primary": "#95d3ba",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d5e6df",
        "text-primary": "#1F2937",
        "on-secondary-fixed-variant": "#3b4a44",
        "on-primary-container": "#80bea6",
        "primary-container": "#064e3b",
        "on-surface-variant": "#404944",
        "error": "#ba1a1a",
        "secondary": "#52625c",
        "surface-container": "#eceeeb",
        "surface-container-low": "#f2f4f1"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-margin": "1.25rem",
        "stack-lg": "2rem",
        "section-padding": "1.5rem",
        "stack-md": "1rem",
        "gutter-md": "1rem",
        "stack-sm": "0.5rem"
      },
      "fontFamily": {
        "headline-lg": ["Libre Caslon Text", "serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Libre Caslon Text", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "prayer-time-display": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["22px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg": ["36px", {"lineHeight": "44px", "fontWeight": "700"}],
        "prayer-time-display": ["24px", {"lineHeight": "32px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
